%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-pose-cov-ops
Version:        0.3.13
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS pose_cov_ops package

License:        BSD
URL:            https://wiki.ros.org/pose_cov_ops
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-iron-cv-bridge
Requires:       ros-iron-geometry-msgs
Requires:       ros-iron-mrpt-libposes
Requires:       ros-iron-mrpt-libros-bridge
Requires:       ros-iron-nav-msgs
Requires:       ros-iron-rclcpp
Requires:       ros-iron-sensor-msgs
Requires:       ros-iron-std-msgs
Requires:       ros-iron-stereo-msgs
Requires:       ros-iron-tf2
Requires:       ros-iron-ros-workspace
BuildRequires:  cmake3
BuildRequires:  ros-iron-ament-cmake
BuildRequires:  ros-iron-ament-cmake-gmock
BuildRequires:  ros-iron-ament-cmake-gtest
BuildRequires:  ros-iron-ament-cmake-xmllint
BuildRequires:  ros-iron-cv-bridge
BuildRequires:  ros-iron-geometry-msgs
BuildRequires:  ros-iron-mrpt-libposes
BuildRequires:  ros-iron-mrpt-libros-bridge
BuildRequires:  ros-iron-nav-msgs
BuildRequires:  ros-iron-rclcpp
BuildRequires:  ros-iron-ros-environment
BuildRequires:  ros-iron-sensor-msgs
BuildRequires:  ros-iron-std-msgs
BuildRequires:  ros-iron-stereo-msgs
BuildRequires:  ros-iron-tf2
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  gtest-devel
BuildRequires:  ros-iron-ament-lint-auto
BuildRequires:  ros-iron-ament-lint-common
%endif

%description
C++ library for SE(2)/SE(3) pose composition operations with uncertainty

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/iron" \
    -DAMENT_PREFIX_PATH="/opt/ros/iron" \
    -DCMAKE_PREFIX_PATH="/opt/ros/iron" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Sat Oct 26 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.3.13-1
- Autogenerated by Bloom

* Tue Aug 27 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.3.12-1
- Autogenerated by Bloom

* Mon Sep 18 2023 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.3.11-1
- Autogenerated by Bloom

* Thu Apr 20 2023 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.3.10-2
- Autogenerated by Bloom

* Fri Apr 07 2023 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.3.10-1
- Autogenerated by Bloom

* Sat Apr 01 2023 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.3.9-1
- Autogenerated by Bloom

* Tue Mar 21 2023 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.3.8-2
- Autogenerated by Bloom

